# -*- coding: utf-8 -*-
"""twiiter_08/04.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MqPMKFm7Dg8cUNXd4F18GnHCUnpQvtcP
"""

import tweepy as tw
import pandas as pd
import sqlite3



#As credencias da acesso a API
consumer_key = 'JncprOBm430oXJQfy9VDJ2onH'
consumer_secret = 'NVgTgzlMEl1lv17Phc8ObSjqUUzHiE0irMhrK1jPpYYCZQoxdR'
access_token = '1062556015655378944-CV02dvS2KYltntWOuHu1m7jC0fajZN'
access_token_secret = 'EGS1o4iBF4qREBsbpPeUb4iSjn02ReUugc6Tg6Fw2xSR1'
bearer_token = 'AAAAAAAAAAAAAAAAAAAAAFgDlgEAAAAAnWn7Y6Q%2FV3VV9ptlmgo2ecaughw%3DRQYyqcl9CwLXxCijC1ubbK1Qsp6va51JYWeajDylkdkeEuQQqP'

#Criando o cliente 
client = tw.Client(bearer_token ,consumer_key,consumer_secret, access_token, access_token_secret)

#Criando o banco de dados
con = sqlite3.connect("chocolate.db")

#Criando o cursor para se conectar ao banco
cur = con.cursor()

#Buscando os twitter's que possui a palavra 'premierleague'
start = '2023-04-08T08:00:01Z'
end = '2023-04-08T18:00:00Z'
resposta = client.search_recent_tweets(query='chocolate', max_results=100 , start_time=start, end_time=end)

#Tipo da variavel 'resposta' ja com o twitter's
type(resposta)

#armazendo somentes os dados de cada twitter
dados_twitters = resposta.data

#Agora os dados estão em um lista
type(dados_twitters)

#Criando uma tabela para armazendos os dados coletados
#(Comando para criar tabela ( nome_da_coluna tipo_da_colana))
cur.execute("CREATE TABLE dados (TEXTO TEXT, RETWEET TEXT)")

#Realizando um for para  obter cada twitter e também para informar quais linhas são retweet e no final adicionar ao banco de dados
for i in dados_twitters:
  TEXTO = i.text
  if (TEXTO [:2] == 'RT' ):
    RETWEET == 'Sim'
  else:
    RETWEET == 'Não'

  cur.execute("INSERT INTO dados (TEXTO, RETWEET) VALUES (?,?)",(TEXTO ,RETWEET))

con.commit()

#comando para saltar a alteração realizada no banco
con.commit()

#fehando a conexão com o banco, como é informado na documentação
con.close()

#criando novamente a conexão com o banco
con = sqlite3.connect('chocolate.db')

cur = con.cursor()

#Executando uma query para exibir todas as colunas da tabela registro
res = cur.execute("SELECT * FROM dados")

df = res.fetchall()

#Transformando a consulta em um dataframe com o pandas

df = res.fetchall()
informacoes = pd.DataFrame(df)

df

#Transformando os dados em um dataframe com o pandas
dados_dataframe = pd.DataFrame(df)
dados_dataframe

dados_dataframe

dados_dataframe.columns = ['Texto','Retweet']

display(dados_dataframe)

#exportando para excel
dados_dataframe.to_excel('twitter.xlsx')

